#!/usr/bin/python
import math

import psutil


def convert_size(size_bytes):
    if size_bytes == 0:
        return "0B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    i = int(math.floor(math.log(size_bytes, 1024)))
    p = math.pow(1024, i)
    s = round(size_bytes / p, 2)
    return "%s %s" % (s, size_name[i])


disks = psutil.disk_io_counters(perdisk=True)
for key, value in disks.items():
    print(f"------ {key} ------")
    print(f"Read: {convert_size(value.read_bytes)}")
    print(f"Write: {convert_size(value.write_bytes)}")
    print(f"-------------------")
